#!/usr/bin/env bash
# script that outputs domain and subdomain of a given domain name

info() {
	dig "$2.$1" | awk '/;; ANSWER SECTION/ {getline;
	printf "The subdomain %s is a %s record and points to %s\n", dom, $4, $5}' dom="$2"
}
if [ $# -gt 1 ]
then
	info "$1" "$2"
else
	info "$1" "www"
	info "$1" "lb-01"
	info "$1" "web-01"
	info "$1" "web-02"
fi

