#!/usr/bin/env bash
#Installs and configure NGINX
apt-get update
apt-get -y install nginx
mkdir /redirect_me
touch /redirect_me/index.html
echo "https://www.youtube.com/watch?v=QH2-TGUlwu4" > /redirect_me/index.html
service nginx restart
