#!/usr/bin/env bash
# Bash script installs nginx and sets up curl to return Hello World

apt-get update
apt-get -y install nginx
sed -i '24 i \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4i permanent;' /etc/nginx/sites-enabled/default
service nginx restart
