#!/usr/bin/env bash
# Bash script installs nginx and sets up curl to return Hello World

apt-get update
apt-get -y install nginx
touch /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i '26 i \\terror_page /usr/share/nginx/html/404.html;' /etc/nginx/sites-enabled/default
service nginx restart
