#!/usr/bin/env bash
#change HTTP header response to know which server gave the response
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed -i "46i\add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
