#!/usr/bin/env bash
#install and configure haproxy loadbalancer
apt install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.4 -y
apt-get -y update
apt install -y haproxy=2.4.\*
echo "ENABLED=1" >> /etc/haproxy/haproxy.cfg
echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver

backend webserver
    balance roundrobin
    server 3211-web-01 35.196.44.201:80 check
    server 3211-web-02 18.208.171.12:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart

