#!/usr/bin/env bash
#install and configure haproxy loadbalancer
apt-get -y update
apt-get -y install haproxy=2.0.13*
echo "
frontend Local_Server
    bind *:80
    mode http
    default_backend hbtn_backend

backend hbtn_backend
    balance roundrobin
    server 3211-web-01 35.196.44.201:80 check
    server 3211-web-02 18.208.171.12:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
