#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
x=1
while [ $x -le 20 ]
do
	if [ $x == 4 ]; then
		echo "$x"
		echo "bad luck from China"
	elif [ $x == 9 ]; then
		echo "$x"
		echo "bad luck from Japan"
	elif [ $x == 17 ]; then
		echo "$x"
		echo "bad luck from Italy"
	else
		echo "$x"
	fi
	(( x++ ))
done
