#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
x=1
while [ $x -le 20 ]
do
	case $x in
		4) echo "bad luck in China" ;;
		9) echo "bad luck in Japan" ;;
		17) echo "bad luck from Italy" ;;
		*) echo $x
	esac
	
	(( x++ ))
done
