#!/usr/bin/env bash
# gives information about the school file
if [ ! -e school ]
then
	echo "school file does not exist"
elif [ -e school ]
then
	echo "school file exist"
elif [ ! -s school ]
then
	echo "school file is empty"
elif [ -s school ]
then
	echo "school file is not empty"
elif [ -f school ]
then
	echo "school file is a regular file"
fi

