#!/usr/bin/env bash
# gives information about the school file
if [ -e school ]; then
	echo "school file exists"
	if [ -s school ]; then
		echo "school file is not empty"
	elif [ ! -s school ]; then
		echo "school file is empty"
	elif [ -f school ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
