#!/usr/bin/env bash
#script that changes what facebook.com and localhost resolves to
cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.new
sed -i "/facebok.com/d" ~/hosts.new
sed -i "1 a 8.8.8.8\t\tfacebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
